language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-harp-browserify' ]; then cd .. && eval "mv $currentfolder generator-harp-browserify" && cd generator-harp-browserify; fi

